import { useState } from 'react'; import { Platform, Text, View } from 'react-native'; import DateTimePicker from '@react-native-community/datetimepicker';
import Screen from '../components/Screen'; import { Button, Field, Title, uiStyles } from '../components/UI'; import { appointmentsApi } from '../api/services'; import { getApiError } from '../api/client'; import { dateTime, money, toApiDateTime } from '../utils/format';

export default function NewAppointmentScreen({ route, navigation }) {
  const { salon, service, employee } = route.params; const [date, setDate] = useState(() => { const d = new Date(); d.setDate(d.getDate() + 1); d.setHours(10, 0, 0, 0); return d; }); const [picker, setPicker] = useState(null); const [notes, setNotes] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const change = (_, value) => { if (Platform.OS !== 'ios') setPicker(null); if (!value) return; const next = new Date(date); if (picker === 'date') next.setFullYear(value.getFullYear(), value.getMonth(), value.getDate()); else next.setHours(value.getHours(), value.getMinutes(), 0, 0); setDate(next); };
  async function submit() { if (loading) return; setLoading(true); setError(''); try { const { data } = await appointmentsApi.create({ funcionarioId: employee.id, servicoId: service.id, dataHora: toApiDateTime(date), observacoes: notes.trim() || null }); navigation.replace('AppointmentConfirmation', { appointment: data }); } catch (e) { setError(e.response?.status === 409 ? 'Esse horário ficou indisponível. Escolha outro horário.' : getApiError(e, 'Não foi possível criar o agendamento.')); } finally { setLoading(false); } }
  return <Screen><Title subtitle="O horário será validado pelas regras do estabelecimento.">Revise seu agendamento</Title><Text style={{ fontWeight: '800' }}>{salon.nome}</Text><Text>{service.nome} • {money(service.preco)} • {service.duracao} min</Text><Text>{employee.nome}</Text><Text style={{ marginVertical: 16, fontSize: 18 }}>{dateTime(date)}</Text><View style={{ flexDirection: 'row', gap: 8 }}><View style={{ flex: 1 }}><Button title="Escolher data" secondary onPress={() => setPicker('date')} /></View><View style={{ flex: 1 }}><Button title="Escolher hora" secondary onPress={() => setPicker('time')} /></View></View>{picker ? <DateTimePicker value={date} mode={picker} minimumDate={picker === 'date' ? new Date() : undefined} is24Hour onChange={change} /> : null}<Field label="Observações (opcional)" value={notes} onChangeText={setNotes} multiline maxLength={255} />{error ? <Text style={uiStyles.error}>{error}</Text> : null}<Button title={loading ? 'Confirmando...' : 'Confirmar agendamento'} disabled={loading} onPress={submit} /></Screen>;
}
